/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author frank lou
 */
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.DB;

public class Admin extends javax.swing.JFrame {

    private DB db;
    private boolean isEditing = false;
    private String adminId;
    
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        initDB();
    }
    
    public void initDB(){
        this.db = new DB();
        this.loadTable(false);
        
               
        this.deleteBtn.setEnabled(false);
        this.newBtn.setEnabled(false);
    }
    
    
    public void loadTable(boolean searching){
        String query ="SELECT * FROM admins";
        
        if (searching){
            String txt = searchTxt.getText();
            query += " WHERE admins.username LIKE '%" + txt + "%'";
        } 

        ArrayList<String[]> data = db.select(query, new String[]{"id","username","password"});
        
        DefaultTableModel model = (DefaultTableModel)this.adminTable.getModel();
        
        model.setRowCount(0);
        
        data.forEach((row) -> {
            String hash = "", ps = row[2];
            
            for (int i = 0; i < ps.length(); i++) 
                hash += "*";
            
            row[2] = hash;
            model.addRow(row);
        });
        

    }
    
    public void resetFields(){
        this.newBtn.setEnabled(false);
        this.deleteBtn.setEnabled(false);
        this.loadTable(false);
        this.passwordTxt.setText("");
        this.isEditing = false;
        this.adminId = "";
        this.usernameTxt.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminTable = new javax.swing.JTable();
        searchTxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        newBtn = new javax.swing.JButton();
        usernameTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Programs CRUD");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        adminTable.setAutoCreateRowSorter(true);
        adminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "USERNAME", "PASSWORD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        adminTable.setToolTipText("Admin Table");
        adminTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        adminTable.setFocusable(false);
        adminTable.setGridColor(new java.awt.Color(255, 255, 255));
        adminTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        adminTable.setRowHeight(27);
        adminTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        adminTable.setSelectionForeground(new java.awt.Color(51, 51, 51));
        adminTable.setShowHorizontalLines(false);
        adminTable.setShowVerticalLines(false);
        adminTable.setSurrendersFocusOnKeystroke(true);
        adminTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adminTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 82, 600, 490);

        searchTxt.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        searchTxt.setBorder(null);
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
        });
        jPanel1.add(searchTxt);
        searchTxt.setBounds(20, 30, 350, 30);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(20, 60, 360, 20);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Username");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 40, 90, 20);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(20, 100, 200, 10);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(20, 170, 200, 20);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Password");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 110, 90, 20);

        deleteBtn.setBackground(new java.awt.Color(204, 204, 204));
        deleteBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(null);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel2.add(deleteBtn);
        deleteBtn.setBounds(20, 520, 200, 40);

        saveBtn.setBackground(new java.awt.Color(204, 204, 204));
        saveBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.setBorder(null);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel2.add(saveBtn);
        saveBtn.setBounds(20, 420, 200, 40);

        newBtn.setBackground(new java.awt.Color(204, 204, 204));
        newBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        newBtn.setText("New");
        newBtn.setBorder(null);
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });
        jPanel2.add(newBtn);
        newBtn.setBounds(20, 470, 200, 40);

        usernameTxt.setBackground(new java.awt.Color(204, 204, 204));
        usernameTxt.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        usernameTxt.setBorder(null);
        jPanel2.add(usernameTxt);
        usernameTxt.setBounds(20, 70, 200, 30);

        passwordTxt.setBackground(new java.awt.Color(204, 204, 204));
        passwordTxt.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        passwordTxt.setBorder(null);
        jPanel2.add(passwordTxt);
        passwordTxt.setBounds(20, 140, 200, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String username = this.usernameTxt.getText();
        String password = String.valueOf(this.passwordTxt.getPassword());
        
        String query = "";
        if (!isEditing){
            query = String.format(
                "INSERT INTO admins(username,password) VALUES ('%s','%s')",
                username, password
            );
        } else {
            query = String.format(
                "UPDATE programs SET username='%s', password='%s' WHERE id=%s",
                username, password , adminId
            );
        }
        
        
        if (db.query(query)){
            this.resetFields();
            JOptionPane.showMessageDialog(this, "Admin was saved successfully","Success!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Error in adding a data to the database","Error!", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        this.resetFields();
    }//GEN-LAST:event_newBtnActionPerformed

    private void adminTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminTableMouseClicked
        this.isEditing = true;
        this.newBtn.setEnabled(true);
        this.deleteBtn.setEnabled(true);
        int row = this.adminTable.getSelectedRow();
        
        this.adminId = this.adminTable.getValueAt(row, 0).toString();
        String username = this.adminTable.getValueAt(row, 1).toString();
        String password = this.adminTable.getValueAt(row, 2).toString();
        
        this.passwordTxt.setText(password);
        this.usernameTxt.setText(username);
        
    }//GEN-LAST:event_adminTableMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int sure = JOptionPane.showConfirmDialog(this, "Are you sure?", "Delete confirmation.", JOptionPane.WARNING_MESSAGE);
        
        adminId = adminTable.getValueAt(adminTable.getSelectedRow(), 0).toString();
        
        if (sure == 0){
            boolean success = db.query(String.format("DELETE FROM admins WHERE id=%s", adminId));
            if (success){
                this.resetFields();
                JOptionPane.showMessageDialog(this, "Admin was deleted successfully","Success!", JOptionPane.INFORMATION_MESSAGE);
            } else 
                JOptionPane.showMessageDialog(this, "Deletion Error.","Error!", JOptionPane.ERROR_MESSAGE);
        
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
        this.loadTable(true);
    }//GEN-LAST:event_searchTxtKeyReleased
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adminTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton newBtn;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
