/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author frank lou
 */
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.DB;

public class Student extends javax.swing.JFrame {

    private DB db;
    private ArrayList<String[]> programs;
    private boolean isEditing = false;
    private String studentId;
    
    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        initDB();
    }
    
    public void initDB(){
        this.db = new DB();
        this.loadTable(false);
        
        // we need to load the programs
        ArrayList<String[]> programs = db.select("SELECT * FROM programs", new String[]{"id","initials"});
      // setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        DefaultComboBoxModel model = (DefaultComboBoxModel)this.programCombo.getModel();
        programs.forEach((row) -> {
            model.addElement(row[1]);
        });
        this.programCombo.setModel(model);
        this.programs = programs;
        
        this.deleteBtn.setEnabled(false);
        this.newBtn.setEnabled(false);
    }
    
    
    public void loadTable(boolean searching){
        String query ="SELECT students.*, programs.initials FROM students LEFT JOIN programs ON students.programId=programs.id";;
        
        if (searching){
            String txt = searchTxt.getText();
            query += " WHERE students.firstName LIKE '%" + txt + 
                    "%' OR students.lastName LIKE '%"+ txt + 
                    "%' OR students.middleName LIKE '%"+ txt +
                    "%' OR programs.initials LIKE '%"+ txt + 
                    "%' OR students.gender LIKE '%" + txt + "%'";
        } 

        ArrayList<String[]> data = db.select(query, new String[]{"id","firstName","lastName","middleName","gender","initials"});
        
        DefaultTableModel model = (DefaultTableModel)this.studentTable.getModel();
        
        model.setRowCount(0);
        
        data.forEach((row) -> {
            model.addRow(row);
        });
        

    }
    
    public void resetFields(){
        this.newBtn.setEnabled(false);
        this.deleteBtn.setEnabled(false);
        this.loadTable(false);
        this.firstNameTxt.setText("");
        this.lastNameTxt.setText("");
        this.middleNameTxt.setText("");
        this.genderCombo.setSelectedIndex(0);
        this.programCombo.setSelectedIndex(0);
        this.isEditing = false;
        this.studentId = "";

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        searchTxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lastNameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        middleNameTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        programCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        genderCombo = new javax.swing.JComboBox<>();
        deleteBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        newBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student CRUD");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        studentTable.setAutoCreateRowSorter(true);
        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FIRST NAME", "LAST NAME", "MIDDLE NAME", "GENDER", "PROGRAM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentTable.setToolTipText("Student Table");
        studentTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        studentTable.setFocusable(false);
        studentTable.setGridColor(new java.awt.Color(255, 255, 255));
        studentTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        studentTable.setRowHeight(27);
        studentTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        studentTable.setSelectionForeground(new java.awt.Color(51, 51, 51));
        studentTable.setShowHorizontalLines(false);
        studentTable.setShowVerticalLines(false);
        studentTable.setSurrendersFocusOnKeystroke(true);
        studentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 82, 600, 490);

        searchTxt.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        searchTxt.setBorder(null);
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
        });
        jPanel1.add(searchTxt);
        searchTxt.setBounds(20, 30, 350, 30);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(20, 60, 360, 20);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("First Name");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 40, 90, 20);

        firstNameTxt.setBackground(new java.awt.Color(204, 204, 204));
        firstNameTxt.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        firstNameTxt.setBorder(null);
        jPanel2.add(firstNameTxt);
        firstNameTxt.setBounds(20, 70, 200, 30);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(20, 100, 200, 10);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(20, 170, 200, 10);

        lastNameTxt.setBackground(new java.awt.Color(204, 204, 204));
        lastNameTxt.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        lastNameTxt.setBorder(null);
        jPanel2.add(lastNameTxt);
        lastNameTxt.setBounds(20, 140, 200, 30);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Last Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 110, 90, 20);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Middle Name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 180, 110, 20);

        middleNameTxt.setBackground(new java.awt.Color(204, 204, 204));
        middleNameTxt.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        middleNameTxt.setBorder(null);
        jPanel2.add(middleNameTxt);
        middleNameTxt.setBounds(20, 210, 200, 30);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(20, 240, 200, 10);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Program");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 330, 90, 20);

        programCombo.setBackground(new java.awt.Color(204, 204, 204));
        programCombo.setToolTipText("");
        programCombo.setBorder(null);
        jPanel2.add(programCombo);
        programCombo.setBounds(20, 360, 200, 40);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Gender");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 250, 90, 20);

        genderCombo.setBackground(new java.awt.Color(204, 204, 204));
        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        genderCombo.setToolTipText("");
        genderCombo.setBorder(null);
        jPanel2.add(genderCombo);
        genderCombo.setBounds(20, 280, 200, 40);

        deleteBtn.setBackground(new java.awt.Color(204, 204, 204));
        deleteBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(null);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel2.add(deleteBtn);
        deleteBtn.setBounds(20, 520, 200, 40);

        saveBtn.setBackground(new java.awt.Color(204, 204, 204));
        saveBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.setBorder(null);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel2.add(saveBtn);
        saveBtn.setBounds(20, 420, 200, 40);

        newBtn.setBackground(new java.awt.Color(204, 204, 204));
        newBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        newBtn.setText("New");
        newBtn.setBorder(null);
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });
        jPanel2.add(newBtn);
        newBtn.setBounds(20, 470, 200, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String firstName = this.firstNameTxt.getText();
        String lastName = this.lastNameTxt.getText();
        String middleName = this.middleNameTxt.getText();
        String gender = this.genderCombo.getSelectedItem().toString();
        String programId = this.programs.get(this.programCombo.getSelectedIndex())[0];
        
        String query = "";
        if (!isEditing){
            query = String.format(
                "INSERT INTO students(firstName,lastName,middleName,gender,programId) VALUES ('%s','%s','%s','%s','%s')",
                firstName, lastName, middleName, gender, programId
            );
        } else {
            query = String.format(
                "UPDATE students SET firstName='%s', lastName='%s', middleName='%s', gender='%s', programId='%s' WHERE id=%s",
                firstName, lastName, middleName, gender, programId, studentId
            );
        }
        
        
        if (db.query(query)){
            this.resetFields();
            JOptionPane.showMessageDialog(this, "Student was saved successfully","Success!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Error in adding a data to the database","Error!", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        this.resetFields();
    }//GEN-LAST:event_newBtnActionPerformed

    private void studentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTableMouseClicked
        this.isEditing = true;
        this.newBtn.setEnabled(true);
        this.deleteBtn.setEnabled(true);
        int row = this.studentTable.getSelectedRow();
        
        this.studentId = this.studentTable.getValueAt(row, 0).toString();
        String firstName = this.studentTable.getValueAt(row, 1).toString();
        String lastName = this.studentTable.getValueAt(row, 2).toString();
        String middleName = this.studentTable.getValueAt(row, 3).toString();
        String gender = this.studentTable.getValueAt(row, 4).toString();
        String program = this.studentTable.getValueAt(row, 5).toString();
        
        this.firstNameTxt.setText(firstName);
        this.lastNameTxt.setText(lastName);
        this.middleNameTxt.setText(middleName);
        this.genderCombo.setSelectedItem(gender);
        this.programCombo.setSelectedItem(program);
    }//GEN-LAST:event_studentTableMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int sure = JOptionPane.showConfirmDialog(this, "Are you sure?", "Delete confirmation.", JOptionPane.WARNING_MESSAGE);
        
        studentId = studentTable.getValueAt(studentTable.getSelectedRow(), 0).toString();
        
        if (sure == 0){
            boolean success = db.query(String.format("DELETE FROM students WHERE id=%s", studentId));
            if (success){
                this.resetFields();
                JOptionPane.showMessageDialog(this, "Student was deleted successfully","Success!", JOptionPane.INFORMATION_MESSAGE);
            } else 
                JOptionPane.showMessageDialog(this, "Deletion Error.","Error!", JOptionPane.ERROR_MESSAGE);
        
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
        this.loadTable(true);
    }//GEN-LAST:event_searchTxtKeyReleased



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JTextField middleNameTxt;
    private javax.swing.JButton newBtn;
    private javax.swing.JComboBox<String> programCombo;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable studentTable;
    // End of variables declaration//GEN-END:variables
}
